name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "Features"
    labels:
      - "feature"
  - title: "Enhancement"
    label: "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Documentation"
    label: "documentation"
  - title: "Maintenance"
    label: "maintenance"
change-template: "- $TITLE @$AUTHOR ([#$NUMBER]($URL))"
change-title-escapes: '\<*_&#@'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feature"
      - "enhancement"
  default: patch
exclude-labels:
  - "skip-changelog"
template: |
  ## Changes

  $CHANGES
