name: Build and Upload xbatcher to TestPyPI
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  publish-testpypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    if: github.repository == 'xarray-contrib/xbatcher'

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # fetch all history so that setuptools-scm works
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install build

      - name: Fix up version string for TestPyPI
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        run: |
          sed --in-place "s/node-and-date/no-local-version/g" pyproject.toml

      - name: Build tarball and wheels
        run: |
          python -m build
          echo "Generated files:"
          ls -lh dist/

      - name: Verify the built dist/wheel is valid
        run: |
          python -m pip install --upgrade pip
          python -m pip install dist/xbatcher*.whl
          python -m xbatcher.util.print_versions

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          # verbose: true
