name: Build and Upload xbatcher to TestPyPI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish-testpypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    if: github.repository == 'xarray-contrib/xbatcher'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4.4.0
        name: Install Python
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Fix up version string for TestPyPI
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        run: |
          sed --in-place "/version_scheme/d" pyproject.toml
          sed --in-place "s/dirty-tag/no-local-version/g" pyproject.toml

      - name: Build tarball and wheels
        run: |
          cat pyproject.toml
          python -m build
          echo "Generated files:"
          ls -lh dist/

      - name: Check built artifacts
        run: |
          python -m twine check --strict dist/*
          pwd
          if [ -f dist/xbatcher-0.0.0.tar.gz ]; then
            echo "❌ INVALID VERSION NUMBER"
            exit 1
          else
            echo "✅ Looks good"
          fi

      - name: Verify the built dist/wheel is valid
        run: |
          python -m pip install --upgrade pip
          python -m pip install dist/xbatcher*.whl
          python -m xbatcher.util.print_versions

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          # verbose: true
