name: Build and Upload xbatcher to TestPyPI
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  publish-testpypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    if: github.repository == 'xarray-contrib/xbatcher'

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          # fetch all history so that setuptools-scm works
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install build

      - name: Fix up version string for TestPyPI
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        run: |
          sed --in-place "s/node-and-date/no-local-version/g" pyproject.toml

      - name: Build tarball and wheels
        run: |
          python -m build
          echo "Generated files:"
          ls -lh dist/

      - name: Verify the built dist/wheel is valid
        run: |
          python -m pip install --upgrade pip
          python -m pip install dist/xbatcher*.whl
          python -m xbatcher.util.print_versions

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          # verbose: true
